/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import caminoalsabor.CaminoAlSabor;
import controlador.ListaPlatillo;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Frame para hacer pedido de comida japonesa
 * @author Pamela
 */
public class Comida_japonesa extends javax.swing.JFrame {

    /**
     * Creates new form Comida_japonesa
     */
    public Comida_japonesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPlatillos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEnvoltorio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCubiertos = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Comida Japonesa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Platillo:");

        jComboBoxPlatillos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxPlatillos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sushi", "Ramen", "Yakitori", "Onigiri", "Sachimi", "Soba", "Takoyaki", "Katsudon", "Tempura", "Monjayaki" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de envoltorio:");

        jComboBoxEnvoltorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxEnvoltorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartón", "Plástico" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cubiertos:");

        jComboBoxCubiertos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxCubiertos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxEnvoltorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jComboBoxCubiertos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPagar)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxEnvoltorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCubiertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnRegresar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        int temp=jComboBoxPlatillos.getSelectedIndex();
        int envoltorio=jComboBoxEnvoltorio.getSelectedIndex();
        int cubiertos=jComboBoxCubiertos.getSelectedIndex();
        switch (temp) {
            case 0:
                ListaPlatillo.contiene("Sushi",envoltorio,cubiertos);
                PrintWriter ticket=null;
                String text="""
                            ticket
                            Gracias por su compra
                              
                            Descripción,Precio
                            Sushi,20""";
                try {        
                    ticket=new PrintWriter("ticket.csv");
                    Objects.requireNonNull(ticket).println(text);
                    ticket.close();
                } catch (IOException ex) {
                    Logger.getLogger(CaminoAlSabor.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 1:
                ListaPlatillo.contiene("Ramen",envoltorio,cubiertos);
                PrintWriter ticket1=null;
                String text1="""
                            ticket
                            Gracias por su compra
                              
                            Descripción,Precio
                            Ramen,135""";
                try {        
                    ticket1=new PrintWriter("ticket1.csv");
                    Objects.requireNonNull(ticket1).println(text1);
                    ticket1.close();
                } catch (IOException ex) {
                    Logger.getLogger(CaminoAlSabor.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
                
            case 2:
                ListaPlatillo.contiene("Yakitori",envoltorio,cubiertos);
                PrintWriter ticket2=null;
                String text2="""
                            ticket
                            Gracias por su compra
                              
                            Descripción,Precio
                            Yakitori,80""";
                try {        
                    ticket2=new PrintWriter("ticket1.csv");
                    Objects.requireNonNull(ticket2).println(text2);
                    ticket2.close();
                } catch (IOException ex) {
                    Logger.getLogger(CaminoAlSabor.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 3:
                ListaPlatillo.contiene("Onigiri",envoltorio,cubiertos);
                break;
            case 4:
                ListaPlatillo.contiene("Sashimi",envoltorio,cubiertos);
                break;
            case 5:
                ListaPlatillo.contiene("Soba",envoltorio,cubiertos);
                break;
            case 6:
                ListaPlatillo.contiene("Takoyaki",envoltorio,cubiertos);
                break;
            case 7:
                ListaPlatillo.contiene("Katsudon",envoltorio,cubiertos);
                break;
            case 8:
                ListaPlatillo.contiene("Tempura",envoltorio,cubiertos);
                break;
            case 9:
                ListaPlatillo.contiene("Monjayaki",envoltorio,cubiertos);
                break;
            default:
                throw new AssertionError();
        }
        Welcome_cliente ventana=new Welcome_cliente();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu ventana=new Menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comida_japonesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comida_japonesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comida_japonesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comida_japonesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comida_japonesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jComboBoxCubiertos;
    private javax.swing.JComboBox<String> jComboBoxEnvoltorio;
    private javax.swing.JComboBox<String> jComboBoxPlatillos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
