/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ListaPlatillo;
import javax.swing.JOptionPane;
import controlador.ListaUsuario;
import controlador.Platillo;

/**
 *Frame de inicio de empleado
 * @author Pamela
 */
public class Welcome_empleado extends javax.swing.JFrame {

    /**
     * Creates new form Welcome_empleado
     */
    public Welcome_empleado() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnModificarDatos = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        btnAgregarPlatillos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGenerarPlatillos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CAMINO AL SABOR");

        btnModificarDatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificarDatos.setText("Modificar datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });

        btnEliminarCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarCuenta.setText("Eliminar cuenta");
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });

        btnAgregarPlatillos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarPlatillos.setText("Agregar Platillos");
        btnAgregarPlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlatillosActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleado");

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGenerarPlatillos.setText("Generar Platillos");
        btnGenerarPlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPlatillosActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Imprimir base de datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Eliminar Platillos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarPlatillos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerarPlatillos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addGap(155, 155, 155))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(178, 178, 178))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnGenerarPlatillos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnModificarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnEliminarCuenta)
                .addGap(10, 10, 10)
                .addComponent(btnAgregarPlatillos)
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatillosActionPerformed
        CrearPlatillos ventana=new CrearPlatillos();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarPlatillosActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        ListaUsuario.validarEdicion();
        Frm_alta_empleado ventana=new Frm_alta_empleado();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Login ventana=new Login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
        ListaUsuario.eliminar(ListaUsuario.index);
        JOptionPane.showMessageDialog(null, "Se elimino la cuenta");
        Inicio ventana=new Inicio();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    private void btnGenerarPlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPlatillosActionPerformed
        int numPlatillos=(int)(Math.random()*150+50);
        int temp=0;
        for (int i = 0; i < numPlatillos; i++) {
            switch (temp) {
                case 0:
                    ListaPlatillo.crearPozole();
                    temp++;
                    break;
                case 1:
                    ListaPlatillo.crearTacoPastor();
                    temp++;
                    break;
                case 2:
                    ListaPlatillo.crearPambazo();
                    temp++;
                    break;
                case 3:
                    ListaPlatillo.crearTostadaPata();
                    temp++;
                    break;
                case 4:
                    ListaPlatillo.crearTostadaTinga();
                    temp++;
                    break;
                case 5:
                    ListaPlatillo.crearTacoBarbacoa();
                    temp++;
                    break;
                case 6:
                    ListaPlatillo.crearTacoBistec();
                    temp++;
                    break;
                case 7:
                    ListaPlatillo.crearEnchiladas();
                    temp++;
                    break;
                case 8:
                    ListaPlatillo.crearTacoLonganiza();
                    temp++;
                    break;
                case 9:
                    ListaPlatillo.crearTlayuda();
                    temp++;
                    break;
                case 10:
                    ListaPlatillo.crearSushi();
                    temp++;
                    break;
                case 11:
                    ListaPlatillo.crearRamen();
                    temp++;
                    break;
                case 12:
                    ListaPlatillo.crearYakitori();
                    temp++;
                    break;
                case 13:
                    ListaPlatillo.crearOnigiri();
                    temp++;
                    break;
                case 14:
                    ListaPlatillo.crearSashimi();
                    temp++;
                    break;
                case 15:
                    ListaPlatillo.crearSoba();
                    temp++;
                    break;
                case 16:
                    ListaPlatillo.crearTakoyaki();
                    temp++;
                    break;
                case 17:
                    ListaPlatillo.crearKatsudon();
                    temp++;
                    break;
                case 18:
                    ListaPlatillo.crearTempura();
                    temp++;
                    break;
                case 19:
                    ListaPlatillo.crearMonjayaki();
                    temp++;
                    break;
                case 20:
                    ListaPlatillo.crearPizza();
                    temp++;
                    break;
                case 21:
                    ListaPlatillo.crearPasta();
                    temp++;
                    break;
                case 22:
                    ListaPlatillo.crearResoto();
                    temp++;
                    break;
                case 23:
                    ListaPlatillo.crearLasana();
                    temp++;
                    break;
                case 24:
                    ListaPlatillo.crearRavioles();
                    temp++;
                    break;
                case 25:
                    ListaPlatillo.crearPannaCotta();
                    temp++;
                    break;
                case 26:
                    ListaPlatillo.crearGelato();
                    temp++;
                    break;
                case 27:
                    ListaPlatillo.crearCarpaccio();
                    temp++;
                    break;
                case 28:
                    ListaPlatillo.crearTiramisu();
                    temp++;
                    break;
                case 29:
                    ListaPlatillo.crearCapresse();
                    temp=0;
                    break;
                default:
                    ListaPlatillo.crearEnchiladas();
            }
        }
        JOptionPane.showMessageDialog(null, "Se generaron "+numPlatillos+" platillos");
    }//GEN-LAST:event_btnGenerarPlatillosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, ListaPlatillo.mostrar().toString());
        ListaPlatillo.baseDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ListaPlatillo.eliminar(0);
        JOptionPane.showMessageDialog(null, "Se elimino un platillo");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPlatillos;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnGenerarPlatillos;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
